/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9e1zNfkXWLf
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
export function ItemList() {
  return (
    <div className="grid grid-cols-4 gap-4">
      <div className="flex flex-col items-center">
        <img
          alt="White Crocs"
          className="mb-2"
          height="150"
          src="/placeholder.svg"
          style={{
            aspectRatio: "150/150",
            objectFit: "cover",
          }}
          width="150"
        />
        <div className="mb-1 text-xs">멤버십 전용</div>
        <div className="mb-1 text-sm">크록스</div>
        <div className="mb-1 text-xs line-through">64,900원</div>
        <div className="mb-1 text-lg font-bold">37,750원</div>
        <div className="mb-4 text-sm text-red-500">41%</div>
      </div>
      <div className="flex flex-col items-center">
        <img
          alt="Black and Red Crocs"
          className="mb-2"
          height="150"
          src="/placeholder.svg"
          style={{
            aspectRatio: "150/150",
            objectFit: "cover",
          }}
          width="150"
        />
        <div className="mb-1 text-xs">멤버십 전용</div>
        <div className="mb-1 text-sm">크록스</div>
        <div className="mb-1 text-xs line-through">64,900원</div>
        <div className="mb-1 text-lg font-bold">34,650원</div>
        <div className="mb-4 text-sm text-red-500">46%</div>
      </div>
      <div className="flex flex-col items-center">
        <img
          alt="Nike Caps"
          className="mb-2"
          height="150"
          src="/placeholder.svg"
          style={{
            aspectRatio: "150/150",
            objectFit: "cover",
          }}
          width="150"
        />
        <div className="mb-1 text-xs">멤버십 전용</div>
        <div className="mb-1 text-sm">나이키</div>
        <div className="mb-1 text-xs line-through">49,000원</div>
        <div className="mb-1 text-lg font-bold">21,900원</div>
        <div className="mb-4 text-sm text-red-500">55%</div>
      </div>
      <div className="flex flex-col items-center">
        <img
          alt="Blue T-Shirt"
          className="mb-2"
          height="150"
          src="/placeholder.svg"
          style={{
            aspectRatio: "150/150",
            objectFit: "cover",
          }}
          width="150"
        />
        <div className="mb-1 text-xs">멤버십 전용</div>
        <div className="mb-1 text-sm">스파오</div>
        <div className="mb-1 text-xs line-through">19,900원</div>
        <div className="mb-1 text-lg font-bold">5,900원</div>
        <div className="mb-4 text-sm text-red-500">70%</div>
      </div>
      <div className="flex flex-col items-center">
        <img
          alt="Black T-Shirts Pack"
          className="mb-2"
          height="150"
          src="/placeholder.svg"
          style={{
            aspectRatio: "150/150",
            objectFit: "cover",
          }}
          width="150"
        />
        <div className="mb-1 text-xs">멤버십 전용</div>
        <div className="mb-1 text-sm">스파오</div>
        <div className="mb-1 text-xs line-through">15,900원</div>
        <div className="mb-1 text-lg font-bold">7,900원</div>
        <div className="mb-4 text-sm text-red-500">50%</div>
      </div>
      <div className="flex flex-col items-center">
        <img
          alt="White T-Shirt with Print"
          className="mb-2"
          height="150"
          src="/placeholder.svg"
          style={{
            aspectRatio: "150/150",
            objectFit: "cover",
          }}
          width="150"
        />
        <div className="mb-1 text-xs">멤버십 전용</div>
        <div className="mb-1 text-sm">스파오</div>
        <div className="mb-1 text-xs line-through">19,900원</div>
        <div className="mb-1 text-lg font-bold">9,950원</div>
        <div className="mb-4 text-sm text-red-500">50%</div>
      </div>
      <div className="flex flex-col items-center">
        <img
          alt="Travel Experience"
          className="mb-2"
          height="150"
          src="/placeholder.svg"
          style={{
            aspectRatio: "150/150",
            objectFit: "cover",
          }}
          width="150"
        />
        <div className="mb-1 text-xs">멤버십 전용</div>
        <div className="mb-1 text-sm">여행체험</div>
        <div className="mb-1 text-xs line-through">701,000원</div>
        <div className="mb-1 text-lg font-bold">182,000원</div>
        <div className="mb-4 text-sm text-red-500">74%</div>
      </div>
      <div className="flex flex-col items-center">
        <img
          alt="Beige Crocs"
          className="mb-2"
          height="150"
          src="/placeholder.svg"
          style={{
            aspectRatio: "150/150",
            objectFit: "cover",
          }}
          width="150"
        />
        <div className="mb-1 text-xs">멤버십 전용</div>
        <div className="mb-1 text-sm">크록스</div>
        <div className="mb-1 text-xs line-through">59,900원</div>
        <div className="mb-1 text-lg font-bold">33,810원</div>
        <div className="mb-4 text-sm text-red-500">43%</div>
      </div>
    </div>
  );
}
